### ISSUE TITLE
Simple custom commands

### ISSUE THREAD

**Issue by Arnacino** [MirayaProject/miraya#37]
add some commands that can be created via GUI that output a text when the command is written in twitch chat

**Comment by Sclafus** [comment]
This would be very similiar to the Osu>Skins that has been added in [v1.1.0-alpha.2](https://github.com/MirayaProject/miraya/releases/tag/1.1.0-alpha.2) if I got your idea

**Comment by Sclafus** [comment]
tl;dr
simple custom commands include text-only replies. No concatenation with the data coming from gosumemory or other sources, since it would be exponentially more difficult.
