### ISSUE TITLE
Add hyperlink to Twitch's OAuth page in preferences menu

### ISSUE THREAD

**Issue by Lorpi3678** [MirayaProject/miraya#53]
Would it be possible in the preference to set a link on the twitch settings on the OAuth Chat writing?

**Comment by Sclafus** [comment]
If I got this right, you'd like to see 
![image](https://github.com/MirayaProject/miraya/assets/31241607/b4c12d71-2d47-4083-b9cc-ccd767f206ec)
this clickable
with the same url that is provided in the initial setup
![image](https://github.com/MirayaProject/miraya/assets/31241607/ea64f0de-34df-4b1b-ab09-28583ea3c45e)
 Can you confirm?

**Comment by Lorpi3678** [comment]
I can confirm! ^^

**Comment by Lorpi3678** [comment]
yes I confirm it! ^^
