### ISSUE TITLE
[BUG] Theme "auto" does not behave as expected

### ISSUE THREAD

**Issue by Lorpi3678** [MirayaProject/miraya#54]
I have detected a problem with the theme color change, even if the windows theme is set to black miraya remains white.

**Comment by Sclafus** [comment]
Need further info
From my testing, everything should be fine

**Comment by Lorpi3678** [comment]
Excuse me if I didn't explain myself well, what I meant is shown in the video, the light and dark theme of windows is not synchronized with miraya 
(https://cdn.discordapp.com/attachments/682664172189646850/1113356456020955207/2023-05-31_08-27-24.mp4)

**Comment by Sclafus** [comment]
Original video for further reference

https://github.com/MirayaProject/miraya/assets/31241607/79618fb0-4e04-414f-97c3-3c0aa14ed1ab
