### ISSUE TITLE
Add infos in map request in in-game chat

### ISSUE THREAD

**Issue by Arnacino** [MirayaProject/miraya#75]
Add some sort of feedback in the osu!chat to distinguish maps from one another. Something like the title, the map id? idk

**Comment by Sclafus** [comment]
Might be problematic for users to setup, this feature requires adding a OAuth application via the osu! website.
Still looking into it

**Comment by Sclafus** [comment]
Easy to do with [Client Credentials Grant Flow](https://osu.ppy.sh/docs/index.html#client-credentials-grant), since the info is public there is no need to implement an Authorization Code Grant Flow.
Working on it [here](https://github.com/Sclafus/miraya/tree/osu-api)

**Comment by Sclafus** [comment]
Added in [v1.3.0-alpha.1](https://github.com/MirayaProject/miraya/releases/tag/1.3.0-alpha.1)
Give it a go!
